name: NodeJS CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js '15.x'
        uses: actions/setup-node@v3
        with:
          node-version: '15.x'
          cache: 'npm'
      - name: Installing dependencies
        run: npm ci
      - name: Building an application
        run: npm run build
