name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x, 15.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Installing dependencies
        run: npm install
      - name: Building an application
        run: |
          npm build
          npm run build
      - name: Running tests
        run: npm test

  checkstyle:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install and check code style
        run: |
          npm ci
          npm run codestyle
          with:
            reporter: 'github-pr-check'
        env:
          CI: true
